### ISSUE TITLE
 Incompatible return types of true_fn and false_fn

### ISSUE THREAD

**Issue by SmartMachineBay** [xdever/RFCN-tensorflow#22]
Dataset/coco2014
loading annotations into memory...
Done (t=12.48s)
creating index...
index created!
Loaded 82783 COCO images
Dataset/coco2014
loading annotations into memory...
Done (t=8.34s)
creating index...
index created!
Loaded 40504 COCO images
Traceback (most recent call last):
  File "./main.py", line 89, in <module>
    images, boxes, classes = Augment.augment(*dataset.get())
  File "/home/hp03/liyahui/runed_ok_RFCN-tensorflow/Dataset/Augment.py", line 59, in augment
    image, boxes = mirror(image, boxes)
  File "/home/hp03/liyahui/runed_ok_RFCN-tensorflow/Dataset/Augment.py", line 52, in mirror
    return tf.cond(uniform_random < 0.5, lambda: tf.tuple([image, boxes]), lambda: doMirror(image, boxes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1843, in cond
    "Incompatible return types of true_fn and false_fn: {}".format(e))
TypeError: Incompatible return types of true_fn and false_fn: The two structures don't have the same sequence type. First structure has type <type 'list'>, while second structure has type <type 'tuple'>.

please tell me what should i do? thanks!

**Comment by learnbott** [comment]
The problem is in this statement (duh) in Augment.mirror():

`return tf.cond(uniform_random < 0.5, lambda: tf.tuple([image, boxes]), lambda: doMirror(image, boxes))`

I think wrapping the false_fn (the last arg in the tf.cond) with a tf.tuple should do the trick. 

`return tf.cond(uniform_random < 0.5, lambda: tf.tuple([image, boxes]), lambda: tf.tuple(doMirror(image, boxes)))`

This same error also appears in RFCN-tensorflow.Utils.MultiGather.gatherTopK():

`values, indices = tf.cond(isMoreThanK, lambda: tf.nn.top_k(t, k=k, sorted=sorted), lambda: tf.tuple([t, tf.zeros((0,1), tf.int32)]))`

but this change clears the error:

`values, indices = tf.cond(isMoreThanK, lambda: tf.tuple(tf.nn.top_k(t, k=k, sorted=sorted)), lambda: tf.tuple([t, tf.zeros((0,1), tf.int32)]))`

**Comment by liuchuanloong** [comment]
I have same question when test one amage ,the follow is my command, why error?
 `(tensorflow) liuchuanloong@Inspiron-5577:~/amy/RFCN-tensorflow-master$ ./test.py -n export/model -i /home/liuchuanloong/amy/VOC/VOCdevkit/VOC2007/JPEGImages/  -o /home/liuchuanloong/amy/VOC/

Training network from end
('Anchors: ', [[64, 64], [90, 45], [45, 90], [128, 128], [181, 90], [90, 181], [256, 256], [362, 181], [181, 362], [512, 512], [724, 362], [362, 724]])
Traceback (most recent call last):
  File "./test.py", line 52, in <module>
    net = BoxInceptionResnet(image, len(categories), name="boxnet")
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/BoxInceptionResnet.py", line 58, in __init__
    BoxNetwork.__init__(self, nCategories, rpnInput, 16, [32,32], featureInput, 16, [32,32], weightDecay=weightDecay, hardMining=hardMining)
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/BoxEngine/BoxNetwork.py", line 36, in __init__
    self.proposals, self.proposalScores = self.rpn.getPositiveOutputs(maxOutSize=300)
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/BoxEngine/RPN.py", line 230, in getPositiveOutputs
    boxes, scores = self.filterOutputBoxes(self.boxes, self.scores, preNmsCount=preNmsCount, nmsThreshold=nmsThreshold, maxOutSize=maxOutSize)
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/BoxEngine/RPN.py", line 221, in filterOutputBoxes
    scores, boxes = tf.cond(tf.shape(scores)[0] > preNmsCount , lambda: tf.tuple(MultiGather.gatherTopK(scores, preNmsCount, [boxes])), lambda: tf.tuple([scores, boxes]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1819, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1694, in BuildCondBranch
    original_result = fn()
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/BoxEngine/RPN.py", line 221, in <lambda>
    scores, boxes = tf.cond(tf.shape(scores)[0] > preNmsCount , lambda: tf.tuple(MultiGather.gatherTopK(scores, preNmsCount, [boxes])), lambda: tf.tuple([scores, boxes]))
  File "/home/liuchuanloong/amy/RFCN-tensorflow-master/Utils/MultiGather.py", line 30, in gatherTopK
    values, indices = tf.cond(isMoreThanK, lambda: tf.nn.top_k(t, k=k, sorted=sorted), lambda: tf.tuple([t, tf.zeros((0,1), tf.int32)]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1843, in cond
    "Incompatible return types of true_fn and false_fn: {}".format(e))
TypeError: Incompatible return types of true_fn and false_fn: The two structures don't have the same sequence type. First structure has type <class 'tensorflow.python.ops.gen_nn_ops.TopKV2'>, while second structure has type <type 'list'>.
`

**Comment by RobertCsordas** [comment]
Fixed, tested with version 1.4.1, it works.

Thanks for the support :).
