### ISSUE TITLE
Helping! error when run test.py

### ISSUE THREAD

**Issue by hjyMM2018** [xdever/RFCN-tensorflow#34]
when I run test.py ecounter this:

liyirong@liyirong-Alienware-17-R3:~/RFCN-tensorflow$ ./test.py
/home/liyirong/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Training network from end
Anchors:  [[64, 64], [90, 45], [45, 90], [128, 128], [181, 90], [90, 181], [256, 256], [362, 181], [181, 362], [512, 512], [724, 362], [362, 724]]
Traceback (most recent call last):
  File "./test.py", line 56, in <module>
    input = PreviewIO.PreviewInput(opt.i)
  File "/home/liyirong/RFCN-tensorflow/Utils/PreviewIO.py", line 17, in __init__
    if os.path.isdir(self.path):
  File "/home/liyirong/anaconda3/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

I can't figure out ,Can anyone help?

**Comment by zqdeepbluesky** [comment]
hi,I met the same error ,did you fix it?please help me thanks so much.

**Comment by cpoptic** [comment]
Can confirm; also getting the same error

**Comment by daheyinyin** [comment]
you should run like this
./test.py -n export/model -i <input image> -o <output image>
