### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by VellalaVineethKumar** [xdever/RFCN-tensorflow#39]
Traceback (most recent call last):
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/ROIPooling/ROIPoolingWrapper.py", line 21, in <module>
    roiPoolingModule = tf.load_op_library("BoxEngine/ROIPooling/roi_pooling.so")
  File "/home/vvk/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/vvk/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: BoxEngine/ROIPooling/roi_pooling.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    from BoxInceptionResnet import BoxInceptionResnet
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxInceptionResnet.py", line 23, in <module>
    from BoxEngine.BoxNetwork import BoxNetwork
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/__init__.py", line 1, in <module>
    from BoxEngine.BoxNetwork import *
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/BoxNetwork.py", line 17, in <module>
    from BoxEngine.BoxRefinementNetwork import BoxRefinementNetwork
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/BoxRefinementNetwork.py", line 19, in <module>
    from BoxEngine.ROIPooling import positionSensitiveRoiPooling
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/ROIPooling/__init__.py", line 2, in <module>
    from .ROIPoolingWrapper import *
  File "/home/vvk/Music/RFCN-tensorflow-master/BoxEngine/ROIPooling/ROIPoolingWrapper.py", line 23, in <module>
    roiPoolingModule = tf.load_op_library("./roi_pooling.so")
  File "/home/vvk/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/vvk/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./roi_pooling.so: cannot open shared object file: No such file or directory

**Comment by n0obcoder** [comment]
somebody pls reply.

**Comment by BlueWings8** [comment]
have fixe it？ when I run the test.py has the same error and I have use   USE_OLD_EABI=0 make

**Comment by L0ittle** [comment]
You can try to change the version of Tensorflow, I have fixed it when my tensorflow == 1.8.0
