### ISSUE TITLE
I have some problems,can you tell me why?

### ISSUE THREAD

**Issue by siwenji** [xdever/RFCN-tensorflow#5]
Training network from end
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    net = BoxInceptionResnet(image, len(categories), name="boxnet")
  File "/home/vision/jsw/tf/RFCN-tensorflow-master/BoxInceptionResnet.py", line 43, in __init__
    scale_16 = self.googleNet.getOutput("Repeat_1")[:,1:-1,1:-1,:]
  File "/home/vision/jsw/tf/RFCN-tensorflow-master/InceptionResnetV2.py", line 275, in getOutput
    return self.endPoints[name]
KeyError: 'Repeat_1'

**Comment by ananddb90** [comment]
Hello all,
even I am also facing the same problem while running the demo test.py file.
![image](https://cloud.githubusercontent.com/assets/25154012/26391444/1e14d5e8-4063-11e7-8669-62e18786f926.png)

**Comment by RobertCsordas** [comment]
It's probably python2 compatibility issue. I just updated the code to make it compatible with python2. Please check if it fixes your problem.
